### ISSUE TITLE
Cannot find the seed

### ISSUE THREAD

**Issue by sam12boy** [Leanny/SeedSearcher#1]
[the pic](https://imgur.com/NLk9rfe)
I can confirm the stats are all right ,both ivs (I have levelled up to lv100,and give 4evs)and other stats on pokemon.
But when I chose deviation from 0-2,it cannot find the seed.
And the name and rarity options are right.

I don't know if I have done something wrong, or there is a bug?

**Comment by Leanny** [comment]
Sorry for the late response. There are some seeds where seeds cannot be found. If this happens, you should advance by 1 day and then redo the operation.

**Comment by sam12boy** [comment]
thx for your reply,I'll try it

**Comment by Leanny** [comment]
I found the issue and the seed can be obtained with the latest version: F7847E04CD1F94F2
