### ISSUE TITLE
Crash when using CUDA.

### ISSUE THREAD

**Issue by gavros963** [Leanny/SeedSearcher#14]
Had the program crash on starting the search with this error log:
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: [CUDAError] CUDA_ERROR_UNKNOWN
   at Alea.CUDAInterop.cuSafeCall@2939.Invoke(String message)
   at A.cf5aded17df9f7cc4c132234dda010fa7.Copy@918-22.Invoke(Unit _arg9)
   at Alea.Memory.Copy(FSharpOption`1 streamOpt, Memory src, IntPtr srcOffset, Memory dst, IntPtr dstOffset, FSharpOption`1 lengthOpt)
   at Alea.ImplicitMemoryTrackerEntry.cdd2cd00c052408bcdbf03958f14266ca(FSharpFunc`2 c600c458623dca7db199a0e417603dff4, Object cd5116337150ebaa6de788dacd82516fa)
   at Alea.ImplicitMemoryTrackerEntry.c6a75c171c9cccafb084beba315394985(FSharpFunc`2 c600c458623dca7db199a0e417603dff4, Object cd5116337150ebaa6de788dacd82516fa)
   at Alea.ImplicitMemoryTracker.HostReadWriteBarrier(Object instance)
   at A.cf5aded17df9f7cc4c132234dda010fa7.clo@2359-624.Invoke(Object arg00)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at SeedSearcherGui.SeedSearcherGPU.SearchFour(Device device, Int32 start, Int32 end, ToolStripStatusLabel updateLbl)
   at SeedSearcherGui.SeedSearcher.CalculateGPU(Int32 searcherIDX, Int32 minRerolls, Int32 maxRerolls, Int32[] target, ToolStripStatusLabel updateLbl)
   at SeedSearcherGui.SeedSearcherGui.<>c__DisplayClass34_0.<SearchImpl>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeedSearcherGui.SeedSearcherGui.<SearchImpl>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SeedSearcherGui
    Assembly Version: 1.1.1.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/DEXTOP/Desktop/SeedSearcher110b/SeedSearcherGui.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Alea
    Assembly Version: 3.0.0.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/DEXTOP/Desktop/SeedSearcher110b/SeedSearcherGui.exe
----------------------------------------
PKHeX_Raid_Plugin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/DEXTOP/Desktop/SeedSearcher110b/SeedSearcherGui.exe
----------------------------------------
PKHeX.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/DEXTOP/Desktop/SeedSearcher110b/SeedSearcherGui.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
FSharp.Core
    Assembly Version: 4.7.0.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/DEXTOP/Desktop/SeedSearcher110b/SeedSearcherGui.exe
----------------------------------------
Alea.DynamicInterop
    Assembly Version: 0.0.0.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/DEXTOP/Desktop/SeedSearcher110b/SeedSearcherGui.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/DEXTOP/Desktop/SeedSearcher110b/SeedSearcherGui.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Alea.Parallel
    Assembly Version: 3.0.0.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/DEXTOP/Desktop/SeedSearcher110b/SeedSearcherGui.exe
----------------------------------------
Alea.IL
    Assembly Version: 3.0.0.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/DEXTOP/Desktop/SeedSearcher110b/SeedSearcherGui.exe
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Mono.Cecil
    Assembly Version: 0.9.6.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/DEXTOP/Desktop/SeedSearcher110b/SeedSearcherGui.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.`

**Comment by Leanny** [comment]
https://github.com/Leanny/SeedSearcher/blob/master/README.md

**Comment by Leanny** [comment]
Check the Readme, there is a section about this error and what to do: https://github.com/Leanny/SeedSearcher/blob/master/README.md

**Comment by gavros963** [comment]
> Check the Readme, there is a section about this error and what to do: https://github.com/Leanny/SeedSearcher/blob/master/README.md

Ah thanks, should read the readme first, sorry.
