### ISSUE TITLE
Run for hours with no progress

### ISSUE THREAD

**Issue by wearloga** [Leanny/SeedSearcher#15]
I've been running the 1.1b for a few hours and i haven gotten any movement. my computer isn't
slow as its only using about 40% of my CPU. But my iv deviation stays at 0 (set to 0-3) and by calculation time stays at 0ms. are these supposed to stay that way until its finished, or is it supposed to make some sort of progress?

![seedcheckerissue](https://user-images.githubusercontent.com/60771798/74009102-1eb6f080-4948-11ea-9a4e-5b8039ea5fef.jpg)

here is my attempt at searching. is it that these just wont be able to pull the seed? will these work, or will i need to skip ahead and try again?

**Comment by Leanny** [comment]
Hi. Here is your seed: ``9C93F1AC82E8CE0B``
Doing a 4/6 search on CPU can take multiple hours, so its normal that nothing is happening for a while

**Comment by RocoGreen** [comment]
@Leanny I think i have the same problem.
This was working yersterday and i could calculate this seed but now (today), for an unknown reason, the program is blocked for multiple hours on my GPU.
Yersterday, it took me 10 minutes but now it's blocked...

Do you know what is causing this ?

EDIT : My GPU is Nvidia GeForce GTX 1050
