### ISSUE TITLE
can't use chinese

### ISSUE THREAD

**Issue by qhq** [Leanny/SeedSearcher#16]
No reaction after selection

**Comment by qhq** [comment]
and i can't check star for the pokemon ,they are all Milcery(GMAX)……

![QQ截图20200207220225](https://user-images.githubusercontent.com/3319385/74035731-cb9b7700-49f5-11ea-93a5-b5021257e1cd.png)

**Comment by Leanny** [comment]
I will release an update in a bit (when I close this issue). I fixed the bug with Chinese translation and grouped the box a bit
![2020-02-07 15_09_03-Seed Searcher 1 2 pre](https://user-images.githubusercontent.com/1884062/74036089-e3560980-49bb-11ea-8eba-b7089f6f4c51.png)

**Comment by qhq** [comment]
thank you

**Comment by Leanny** [comment]
Here is the new update: https://github.com/Leanny/SeedSearcher/releases/download/1.2pre/SeedSearcher120-pre-b.zip
