### ISSUE TITLE
exception error IV calculator

### ISSUE THREAD

**Issue by scag736** [Leanny/SeedSearcher#18]
hi if i try and use iv calculator for toxtricity when i click apply i get exception error 

screen shot included

![IMG_4949](https://user-images.githubusercontent.com/59627193/74046683-e60a2c00-49c6-11ea-8bda-96a3780ec815.jpg)

**Comment by Leanny** [comment]
Try to use the newest version (it's in the same pre-release page as before but version changed to 1.2 pre b)

**Comment by scag736** [comment]
great thanks for answering so quick works great now. thanks for all your hard work great seedsearcher
