### ISSUE TITLE
SeedSearcher say valid IVs but not

### ISSUE THREAD

**Issue by RocoGreen** [Leanny/SeedSearcher#19]
Hello, i noticed a problem from this software.
For example, here is my toxtricity's IVs :

![image](https://user-images.githubusercontent.com/52676010/74086310-ec111300-4a81-11ea-81b0-4671ec648144.png)

The software say ok but it's not and when i try to search with all theses infos :

![image](https://user-images.githubusercontent.com/52676010/74086324-1236b300-4a82-11ea-94a4-9539f7e4c36a.png)

I'm on my GPU and it's blocked, totally blocked and nothing happends.
I tried with another softwares but they're said the IVs is incorrect but this software not and i think it's a bug.

Can you please try and see what's going on ?

EDIT : This issue has the same problem #15 the software say valid but others not

**Comment by Leanny** [comment]
Looks good to me. Here is your seed ``F7B61CCCF8993556``

**Comment by RocoGreen** [comment]
I think you have a different version, because this is really not working but that works : 

![image](https://user-images.githubusercontent.com/52676010/74093758-c3673880-4ad6-11ea-9782-bbee1619c3f1.png)

And my pc took me only 2 mins to calculate that but what i sent before wasn't working

**Comment by Leanny** [comment]
Please read this: https://github.com/Leanny/SeedSearcher/blob/master/README.md#what-does-46-56-or-66-mean

You did a 4/6 search in the top one which takes up to 32 times more than what you were searching in the second one. 
The one at the top is also at deviation 2, so you would probably need around 3h with the current released version to get the seed

**Comment by RocoGreen** [comment]
Oh i see, i'm sorry, you are right ^^'
