### ISSUE TITLE
Seed Checker is behind by 3 frames.

### ISSUE THREAD

**Issue by Epsilon91** [Leanny/SeedSearcher#20]
The program produced a seed, 26E092EA2206425C, at the Event Den in 12 minutes. The inputs were:
- Day 4: Hattrem 3☆, Bashful, Anticipation, alert to sounds | 29.19.31.31.4.31
- Day 4: Toxtricity-G 4☆, Gentle, Technician, alert to sounds | 15.25.31.31.31.31
- Day 5: Orbeetle-G 3☆, Rash, Telepathy, plenty of siestas | 31.5.31.4.22.31
- Day 6: Milcery-G 4☆, Mild, Sweet Veil, somewhat vain | 31.31.10.31.31.30

In the seed checker tab, it tells me my starting frame is 3 ahead from what it actually is. For example, the Day 4 Pokémon above is listed as being on 6 Frame Advances. The seed should have been AEC8A74989DE816D.

**Comment by Leanny** [comment]
Are you using gpu or cpu search? I will take a look at this

**Comment by RocoGreen** [comment]
@Epsilon91 You mean for example the first pokemon so the 0 frame in seed checker tab is before 3 frames ?

**Comment by RocoGreen** [comment]
I checked and i confirm, the list is weird. When i passed some days to get my shiny frame, my shiny was not at the frame where the list mentionned it.
So i passed 42 days to be in my shiny frame.

Do you know how to fix that Leanny ?

**Comment by Leanny** [comment]
Will be fixed later today. For now what you can do is to change the dates for the search. If you do a search with day 4-5-6 then set them to 1-2-3 for now

**Comment by RocoGreen** [comment]
Thank you for this fastest response ^^

**Comment by Epsilon91** [comment]
Thanks for the fast response, Leanny. I don't know if it searched via GPU / CPU. I'm on a gaming PC, and never got the CUDA Error. The search is pretty fast in my opinion.

Also, the discrepancy didn't stop me from getting to the shiny frame, but I simply had to subtract 3 advances from what the Seed Checker was telling me for the seed it produced.

**Comment by RocoGreen** [comment]
Yep ! You are right. So, if someone want a fix, there he is :

- Step 1 :
Copy the seed from frame 2 in the list
▫️ Example : 
![image](https://user-images.githubusercontent.com/52676010/74149269-aa11d980-4c07-11ea-9014-149d3b2980c6.png)

- Step 2 :
Set this seed in seed checker tab

- Step 3 :
E N J O Y

**Comment by RocoGreen** [comment]
@Leanny The new version doesn't fix this issue for GPU.
I'm using Nvidia GeForce GTX 1050 (CUDA) and the list is before 3 frames.

Please, can you fix that for GPU ?

**Comment by Leanny** [comment]
I am pretty sure this is fixed. Can you send me an input to reproduce the issue?

**Comment by RocoGreen** [comment]
Weird, I searched again and the issue fixed itself.
So, sorry for this fake alert ^^'
