### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by qhq** [Leanny/SeedSearcher#22]
![snipaste20200210_170224](https://user-images.githubusercontent.com/3319385/74135569-7d6dba00-4c27-11ea-9dab-4d88494e046e.png)
![snipaste20200210_170242](https://user-images.githubusercontent.com/3319385/74135572-7f377d80-4c27-11ea-9197-35b2a36832ff.png)

**Comment by Leanny** [comment]
Could you tell me what the error for the top one is? The bottom one is double character I guess, but I don't know what is wrong with the top one

**Comment by qhq** [comment]
81 Giant's Mirror ,chinese is 巨人镜池。
and 92 Giant's Cap, chinese is 巨人帽岩。
Two translations are reversed

**Comment by qhq** [comment]
and 70 is 巨石原野 C（60 is E）

**Comment by Leanny** [comment]
![2020-02-10 18_51_09-Seed Searcher 1 2 pre - b](https://user-images.githubusercontent.com/1884062/74175543-536fc400-4c36-11ea-970f-8c5530b43cf6.png)
![2020-02-10 18_50_22-Seed Searcher 1 2 pre - b](https://user-images.githubusercontent.com/1884062/74175492-3fc45d80-4c36-11ea-995d-a7d561f4cdc6.png)

Is this correct now?

**Comment by qhq** [comment]
it's right
