### ISSUE TITLE
Possible swapped data for 20-03-09 Event 

### ISSUE THREAD

**Issue by Makai** [Leanny/SeedSearcher#35]
I've got a 4-star Shield G-Max Snorlax on frame 0 of a 20-03-09 event den with seed c0dcf1c654e26c40 but the stats on the 4th frame do not match what's on the calculator (31 | 7 | 31 | 31 | 31 | 1 | Lax). 
It does however match the 4th frame stats on the calculator's 3-star G-Max Snorlax (20 | 3 | 31 | 31 | 31 | 8 | Gentle). 
Which leads me to believe that the data for 3-star and 4-star G-Max Snorlax for this event are probably incorrectly swapped.

**Comment by Leanny** [comment]
Did you catch a 3 star on frame 4? You need to select the target mon if you want to know the stats on a frame, not the mon you cought

**Comment by Makai** [comment]
Ah, looks like I definitely misunderstood something. 
Ran through it again and caught a 4-star on frame 4 and it matched correctly.
Sorry about that!
