### ISSUE TITLE
Feature Request: Seed Searcher QoL Stuff

### ISSUE THREAD

**Issue by Th3Alic3** [Leanny/SeedSearcher#37]
Hey!

There are a few quality of life recommendations/requests for the Seed Searcher.

1. Nature Filter
After using Fish's search tool, I feel many users would agree the ability to select multiple natures would be helpful. Since the introduction of Mints to the series, I tend to filter my raids to Neutral Nature (Quirky, Bashful, Serious, Docile, & Hardy) Pokémon as they do not have the Pinch Berry drawback for competitive battles.

While I would be happy for an in-term addition to the drop down of "Neutral Natures", I imagine some people prefer the ability to choose between multiple natures for the filter.

2. Ability Filter
I would like to request an option added to the Ability Filter for Non-Hidden Ability. For Pokémon with two main abilities to whom the Hidden Ability is not wanted there is no option to search for JUST those two. Since an Ability Capsule can swap between Ability 1 & 2, an option to search for just those abilities would be great.

3. Ability Results Simplified
I would like to request a toggle for the output results to instead of showing the name of an ability to show either "Ability 1", "Ability 2", or "Hidden" as a simplifed output. 

4. Max IV Check Box
Would you be able to add a check box next to each of the six stats that automatically greys out the 0 to 31 in both Min & Max and sets them to 31 both? I feel that would speed up searches for people.

5. Hide Columns
I imagine some users would benefit from an option to hide/omit showing some of the columns from the output (especially if it processed fasted by those omitions ~ which is just wishful thinking). There are some Columns which some people are less do not use or care to know.

I imagine 90% of people do not care for the:
- Characteristics
- Deviation

(I appreciate them being there but scrolling through a search yield of 250000 results is a bit much without having to scroll left and right as well!)

Thanks in advance

**Comment by Leanny** [comment]
I swear I thought 2 is already a thing, but I guess not. All of your requested additions sound reasonable (from an enduser and programmers perspective) so I will take care of them for the next release

**Comment by Leanny** [comment]
Ill keep track of nr 5 in a seperate issue. The other 4 are done

**Comment by Leanny** [comment]
Note: 3 is only a "barely okay". I display (1), (2) and (H) but did not add the ability to simplify it. I need to rewrite a bit more code for it which is TBD for another revision
