### ISSUE TITLE
Issue: Error Selecting Den 156 & Lycanroc/Gourgeist Forms

### ISSUE THREAD

**Issue by Th3Alic3** [Leanny/SeedSearcher#38]
![image](https://user-images.githubusercontent.com/57371173/85211983-1a8ddd00-b303-11ea-9361-79f986fb8a1f.png)

Hey,

I included a screen cap as the app continously produces the same error when attempting to select Den 136.

(There's also issues with the Lycanroc family form OR Gourgeist family form for the species in the app but I will open up another issue for that.)

Thanks

**Comment by Leanny** [comment]
Looks like I forgot the last nest. Fixed in latest commit
