### ISSUE TITLE
Issue: Multiple Form Pokémon

### ISSUE THREAD

**Issue by Th3Alic3** [Leanny/SeedSearcher#39]
The Seed Searcher listing for Den 136 Rare (Nest 156) only shows two listings for Lycanroc. The website as well as the SciresM's dump indicates at 5 Star there should be 5 difference occurences with all 3 forms.

I currently have the rare form spawned at a value of 99 (aka 100%) which on both Sword & Shield, the rare form (Lycanroc-2) is its "Dusk" which only has the ability "Tough Claws".

You will see in this screen cap from PKHeX with your Raid Plug-In that I do have Dusk (Lycanroc-2) present:
![image](https://user-images.githubusercontent.com/57371173/85212156-c552cb00-b304-11ea-93ba-687b39fb6b0b.png)

The Seed Searcher only lists two entries for Lycanroc to appear at: "4*/5*" & "5*". However, it does not list which form is being searched for.

The search results for both of this selections ONLY show abilities for the two other forms: Lycanroc's Midday Form (Lycanroc-0) & Midnight Forms (Lycanroc-1) [I hope I didn't mix those two up.]

The Nest ID: 6162140483756004486 according to SciresM's dump should have the following spawns (on Shield):
1%~5% Blissey
6%~29% Lycanroc-1
30%~55% Lycanroc-1
56%~75% Lycanroc-0
76%~95% Lycanroc-1
96%-100% Lycanroc-2
_(I assume this means one of the base forms Midday/Midnight is more common on Sword than Shield and vise-versa)_

I attempted to search with the Seed and plugged in the results into PKHeX. The plug in seems to match (only with the correct form showing.)

I will catch it to let you know if there's a difference.

For using the Seed Searcher, it would help a lot if the form numbers were added. Maybe down the road add the form names "Midday", "Midnight", and "Dusk" to the listing if it doesn't bog down the interface. (Same for Rockruff obviously!)

I will also assume this situation replicates with the Pumpkaboo/Gourgeist line as they also specifically appear with their specific "Small", "Average", "Large", and "Super Large" forms as SciresM's dump shows listings for forms 0, 1, 2, & 3 in the raids.

Thanks for the app!! It rocks!

**Comment by Leanny** [comment]
![2020-06-21 12_03_05-Window](https://user-images.githubusercontent.com/1884062/85221823-508c9900-b3b7-11ea-939a-e36e8bad4c47.png)
![2020-06-21 12_05_06-Window](https://user-images.githubusercontent.com/1884062/85221838-7c0f8380-b3b7-11ea-9f5a-9dbc8cac5a9b.png)



From newest commit. This should fix the issue
