### ISSUE TITLE
Option to skip IV deviation range if already calculated

### ISSUE THREAD

**Issue by misklikk** [Leanny/SeedSearcher#4]
Don't know if this is entirely possible, since I don't have insight as to whether or not searches change too much or can't be written to a temporary text file. It's more of an idea rather than an issue.

Idea:

If one has already tried to calculate the possible seeds for an IV deviation of 0-1, when increasing the range to 0-2 (using the same Pokémon and stats), search should be able to skip all previous attempts for the first range by selecting a file which has the previous search attempts written into it.
Don't know, if this is possible, but it would help cut down on search times, as waiting a couple of hours for just a 0-0 deviation to return no seeds (since the 4/6 introduction with 1.0e) can become frustrating.

Or would 2-2 work for the scenario above already as intended?

**Comment by misklikk** [comment]
Or would 1-2 already work as intended?

**Comment by Leanny** [comment]
In this scenario 2-2 is what you want to skip 0 and 1

**Comment by misklikk** [comment]
Assuming that this does work as intended (being able to check one deviation at a time instead of going for a high deviation from the start), you may close this issue. Just haven't really seen anyone covering it (will need to check the README). 

Have found another bug with how and if max. deviation numbers are overwritten, when setting a min. number that is higher than current max. Will reproduce and post here.
