### ISSUE TITLE
possible CUDA 11.1 incompatibility runtime error 

### ISSUE THREAD

**Issue by Replicant-Deckard** [Leanny/SeedSearcher#48]
![image](https://user-images.githubusercontent.com/110702128/200208373-d7af93f7-6ca6-4d13-82e0-245948aede04.png)

I had CUDA 11.1 installed due to me using pytorch a few months back, tried uninstalling it, updating my drivers (RTX 3080) running the CUDA installer folder .bat but to no avail. CPU works tho, its only when using GPU acceleration

import key: 

eyJTZXR1cCI6eyJOZXN0SUQiOjY1LCJHYW1lSUQiOjEsIkV2ZW50SUQiOiIifSwiUGttbjEiOnsiRGF5Ijo3LCJJbmRleCI6MTAsIklWcyI6MTA3MjkyMTY3MCwiTmF0dXJlIjoxNSwiQWJpbGl0eSI6LTEsIkNoYXJhY3RlcmlzdGljIjo1fSwiUGttbjIiOnsiRGF5Ijo3LCJJbmRleCI6MTgsIklWcyI6MTA3Mzc0MTAxNCwiTmF0dXJlIjo5LCJBYmlsaXR5IjoyLCJDaGFyYWN0ZXJpc3RpYyI6NX0sIlBrbW4zIjp7IkRheSI6MSwiSW5kZXgiOjE4LCJJVnMiOjEwNzMyMDgzMTksIk5hdHVyZSI6MjAsIkFiaWxpdHkiOi0xLCJDaGFyYWN0ZXJpc3RpYyI6NH0sIlBrbW40Ijp7IkRheSI6MiwiSW5kZXgiOjEwLCJJVnMiOjgzODgzMjQ0NywiTmF0dXJlIjo1LCJBYmlsaXR5IjotMSwiQ2hhcmFjdGVyaXN0aWMiOjJ9LCJDaGVja3N1bSI6NjczNX0=

**Comment by Replicant-Deckard** [comment]
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Unknown arch: sm86
Loading method as kernel:
-> Method: Alea.Parallel.Device.DeviceFor.[Void Kernel(Int64, Int64, System.Action`1[System.Int64])]
-> InstanceOpt: <None>
-> Argument.#0: 0
-> Argument.#1: 8388608
-> Argument.#2: System.Action`1[System.Int64]
Getting or loading method as kernel:
-> Method: Alea.Parallel.Device.DeviceFor.[Void Kernel(Int64, Int64, System.Action`1[System.Int64])]
-> InstanceOpt: <None>
-> Argument.#0: 0
-> Argument.#1: 8388608
-> Argument.#2: System.Action`1[System.Int64]

   at Alea.Gpu.GetOrLoad(MethodInfo kernelMethodInfo, FSharpOption`1 instanceOpt, FSharpList`1 arguments)
   at Alea.CSharp.GpuExtensions.Launch[T1,T2,T3](Gpu this, Action`3 kernel, LaunchParam lp, T1 arg1, T2 arg2, T3 arg3)
   at SeedSearcherGui.SeedSearcherGPU.SearchFour(Device device, Int32 start, Int32 end, List`1 abilities, ToolStripStatusLabel updateLbl, ToolStripProgressBar calculationProgressBar)
   at SeedSearcherGui.SeedSearcher.CalculateGPU(Int32 searcherIDX, Int32 minRerolls, Int32 maxRerolls, Int32[] target, ToolStripStatusLabel updateLbl, ToolStripProgressBar calculationProgressBar)
   at SeedSearcherGui.SeedSearcher.Calculate(Int32 searcherIDX, Int32 minRerolls, Int32 maxRerolls, Int32[] target, ToolStripStatusLabel updateLbl, ToolStripProgressBar calculationProgressBar)
   at SeedSearcherGui.SeedSearcherGui.<>c__DisplayClass42_0.<SearchImpl>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeedSearcherGui.SeedSearcherGui.<SearchImpl>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SeedSearcherGui
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/Replicant/Downloads/SeedSearcher120-c/SeedSearcher120-c/SeedSearcherGui.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Alea
    Assembly Version: 3.0.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/Replicant/Downloads/SeedSearcher120-c/SeedSearcher120-c/SeedSearcherGui.exe
----------------------------------------
PKHeX_Raid_Plugin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/Replicant/Downloads/SeedSearcher120-c/SeedSearcher120-c/SeedSearcherGui.exe
----------------------------------------
PKHeX.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/Replicant/Downloads/SeedSearcher120-c/SeedSearcher120-c/SeedSearcherGui.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4566.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
FSharp.Core
    Assembly Version: 4.7.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/Replicant/Downloads/SeedSearcher120-c/SeedSearcher120-c/SeedSearcherGui.exe
----------------------------------------
Alea.DynamicInterop
    Assembly Version: 0.0.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/Replicant/Downloads/SeedSearcher120-c/SeedSearcher120-c/SeedSearcherGui.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/Replicant/Downloads/SeedSearcher120-c/SeedSearcher120-c/SeedSearcherGui.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
Alea.Parallel
    Assembly Version: 3.0.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/Replicant/Downloads/SeedSearcher120-c/SeedSearcher120-c/SeedSearcherGui.exe
----------------------------------------
Alea.IL
    Assembly Version: 3.0.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/Replicant/Downloads/SeedSearcher120-c/SeedSearcher120-c/SeedSearcherGui.exe
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Mono.Cecil
    Assembly Version: 0.9.6.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/Replicant/Downloads/SeedSearcher120-c/SeedSearcher120-c/SeedSearcherGui.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by Leanny** [comment]
Thank you for the report. Unfortunately I am not able to solve this issue. The GPU library I am using is discontinued and no updates to support newer GPUs has been added to it

**Comment by Replicant-Deckard** [comment]
I see, so the newer rtx will not be supported unless you decide to switch to Open GL i pressume? thanks for the reply :) 

Another question: 
![image](https://user-images.githubusercontent.com/110702128/200359549-2d7372b8-a0cd-465b-b362-868db6808fc5.png)

this is the second time i get no solution to a seed after switching my day 1 to the second and third day... am i doing something wrong? how can I reset day 1 so that i am 100% sure it's the first frame (in case that is the problem)? is a save point ALWAYS stored as frame 1 or how can i troubleshoot this?

**Comment by Leanny** [comment]
Yeah, unfortunately it wont be supported for now. The project is also pretty much dead at this point, but if the new games have a similar raid mechanism, then I will update the tool to support newer GPUs + the new game.

About the second question: Can you send me screenshots of the pokemon you catch? (With all required details like Stats, maybe IV Judge, Ability etc). That way I might be able to figure out if anything is wrong with the input

**Comment by Replicant-Deckard** [comment]
ok sure, im gonna repeat the whole process again and write down all the stats because my game is not in english, will update in like an hour when its done

**Comment by Replicant-Deckard** [comment]
quick question: does it matter if i calculate the IVs by inputting the ranking + stats and then lvling to the suggested lvl and adding the missing values, and so on... or is it adviced to lvl up to 100 instead?

**Comment by Leanny** [comment]
Both work equally well. Just leveling to the suggested level safes you some resources

**Comment by Replicant-Deckard** [comment]
Switched day 1 all the way to 09/11/22 at 22:08 now: did this by saving the game, closed it and opened again

skipping 3 times to day 4 with the "invite others" glitch: 12/11/22; it was a 4 stars ditto so i soft reset the game, set date to 09 and try again. Doesn't work, I try one last time before moving over day 1 again.

I get a 3 star ditto raid on day 4 (12/11/22). I capture it. 

Ditto #1:
HP: Best
ATK: Best
DEF: Decent
SPA: Best
SPD: Decent
SPE: Decent
Ability: Limber
LVL: 36
HP: 91
ATK: 45
DEF: 41
SPA: 55
SPD: 40
SPE: 41
Nature: Modest
Trait: Mischiveous!

Asks to go to LVL 50... DEF: 56; SPD: 54; SPE: 56
Asks to go to LVL 51... SPD: 54... finds IVs, 
![image](https://user-images.githubusercontent.com/110702128/200421220-e312b6cc-e233-44b9-be4a-000176fca278.png)

I apply, check IVs and continue to reset the game and skip ahead again to day 4, This time aiming for a 5 star ditto

I reset my game thrice (again, lucky number) (skip 1 day manually with "find more players", skip 1 day, skip 1 day but its not desirable, so I exit to menu, close game with x button, repeat the entire process) until i finally manage to get a 5 star ditto in day 4 (12/11/22):

Ditto #2:
Best IV HP-SPA
HP: 137
ATK: 76
DEF: 83
SPA: 76
SPD: 55 (Decent)
SPE: 71 (Pretty Good)
Ability: Impostor
Lvl: 56
Nature: Lax
Perk: It's mischiveous!

asks for lvl 58... SPD: 57, SPE: 73
asks for lvl 67... SPD: 65

Finds IVs...

![image](https://user-images.githubusercontent.com/110702128/200426133-6e42e3cb-3776-4afa-9ab7-ea22343aed8c.png)

I click Apply, then confirm IVs

I proceed to find dittos for day 1 and day 2...

Day 1 (9/11/22) is a 3 star ditto... 

HP: Very Good
ATK: Fantastic
DEF: Fantastic
SPA: Best
SPD: Best
SPE: Best

LVL:35
HP: 88
ATK: 49
DEF: 53
SPA: 44
SPD: 49
SPE: 49
Ability: Limber
Nature: Impish
Perk: is alert to sounds!

Asks for lvl 36... HP: 90... 
asks for lvl 38... HP: 94... Finds IVs

![image](https://user-images.githubusercontent.com/110702128/200428348-b9655730-c0cb-4bf3-8ae0-49f7fdb7a3a1.png)

I click Apply and reset the game to now travel to day number 2 (10/11/22)

its a 4 star ditto so i switch day by day doing the "invite more players" every single day until its day 5 (13/11/22)

its a 5 star raid...

Ditto #4:
LVL: 59
HP: 143
ATK: 79
DEF: 66
SPA: 71
SPD: 86
SPE: 62
Ability: Limber
Nature: Careful
Perk: Mischiveous

HP: Best
ATK: Best
DEF: Decent
SPA: Best
SPD: Best
SPE: Decent

Asks for lvl 60... DEF: 67 SPE: 63 
Asks for lvl 67... SPE: 69 
Finds IVs, i click apply 

![image](https://user-images.githubusercontent.com/110702128/200431178-1e39e785-0b87-4165-8127-5a638c940621.png)

Export text:

eyJTZXR1cCI6eyJOZXN0SUQiOjY1LCJHYW1lSUQiOjEsIkV2ZW50SUQiOiIifSwiUGttbjEiOnsiRGF5Ijo0LCJJbmRleCI6MTAsIklWcyI6MTA3MjkyMTY3MCwiTmF0dXJlIjoxNSwiQWJpbGl0eSI6LTEsIkNoYXJhY3RlcmlzdGljIjo1fSwiUGttbjIiOnsiRGF5Ijo0LCJJbmRleCI6MTgsIklWcyI6MTA3Mzc0MTAxNCwiTmF0dXJlIjo5LCJBYmlsaXR5IjoyLCJDaGFyYWN0ZXJpc3RpYyI6NX0sIlBrbW4zIjp7IkRheSI6MSwiSW5kZXgiOjEwLCJJVnMiOjkzODQ0Mjc1MSwiTmF0dXJlIjo4LCJBYmlsaXR5IjotMSwiQ2hhcmFjdGVyaXN0aWMiOjR9LCJQa21uNCI6eyJEYXkiOjUsIkluZGV4IjoxOCwiSVZzIjoxMDcyOTg4MTI5LCJOYXR1cmUiOjIzLCJBYmlsaXR5IjotMSwiQ2hhcmFjdGVyaXN0aWMiOjV9LCJDaGVja3N1bSI6Njc1MH0=


![image](https://user-images.githubusercontent.com/110702128/200431346-52185036-8abc-4c4d-8b7b-001a3bb010dc.png)

For some reason it was stuck with no progress at all... I click stop and click start again and I am able to run 100 calculations in a couple minutes

![image](https://user-images.githubusercontent.com/110702128/200431819-1146608c-649b-4d27-ac9b-d51cc0fbb6c5.png)

I run into the same problem again :/ no luck

![image](https://user-images.githubusercontent.com/110702128/200431993-21ec910a-bafe-428e-ba3b-c32701ed5083.png)

**Comment by Leanny** [comment]
Thank you very much. It's 12am for me now, so I check it tomorrow

**Comment by Replicant-Deckard** [comment]
sure no worries! thanks a lot for taking the time to check it out at all!!

**Comment by Replicant-Deckard** [comment]
also my current day 1 save is the "9/11/22" can I go back to the normal date in my switch and save again on top of it, at "7/11/22" and it will  be day 1 now in "7/11/22" (Today)?

**Comment by Leanny** [comment]
Thank you, I found your issue.

Your seed is (from the first search) `1D1424232B9CA64A` or `9FB6D5984E3A10A5` (2nd search)

First search: Your Ditto on day 2 has ATK and DEF IVs swapped
Second search: That one is weird, your input is correct. Also your search is way too fast for this use case, so there might be a bug with the search itself on your system. The 4/6 search usually takes a lot longer.

You can also go back in time to your actual day now. Your seed should be close to the ones I give (+1 day at most)

**Comment by Replicant-Deckard** [comment]
thank you very much!

**Comment by Replicant-Deckard** [comment]
the second one worked perfectly and i found my pokemon! just one very last question hehe, does this entire process need to be repeated every time i get a max raid from pouring in a wishing stone into a den that has a pokemon i want? or can the seed be used for other dens etc?

IIRC like the seed is fed to an algorithm that is encrypted so i assume we cannot reuse this knowledge after we catch our pokemon and we need to start over... right? thanks for all the help and time on clarification

**Comment by Leanny** [comment]
Glad that you found your pokemon!
Unfortunately every den has its own seed, so you need to repeat the process every time
