### ISSUE TITLE
Weird handling of 2 IV mons

### ISSUE THREAD

**Issue by misklikk** [Leanny/SeedSearcher#6]
Entered this Pokémon first (Nest 89, Sword):

Corvisquire 3*
Modest
Unnerve
Alert to sounds
IVs: 13 17 21 17 31 31

This then demanded a 3 IV mon but with 5/6 (and not 3/6), which would be really hard to get.
The app, however, still accepted the entry (currently calculating with a deviation of 0-4) and the day 5 and 6 mons.

2nd 4th frame mon:

Noctowl 4*
Impish
Keen Eye
Likes to thrash about
IVs: 21 31 17 5 31 31

Is this expected or just a display bug?

**Comment by Leanny** [comment]
5/6 just means the amount of information the spread gives you. You just need to fill the blanks for the 3iv mon. An explanation what 4/6 etc means is in the Readme of this repository
