### ISSUE TITLE
Not sure if a bug or misunderstanding Step 2 in the guide

### ISSUE THREAD

**Issue by EmrXald** [Leanny/SeedSearcher#7]
Hi!

So I caught a corvisquire for the first step. I advanced 3 days(so I end up catching the 4th pokemon in the "queue") and maxed it out to level 100 to get all IV's and such from Serebii. As I checked the IV's I got a result 4/6 and the box below opened up. Here I can't fill in any IV's at all(greyed out) and I can only change between 3* and 4* drifblim. Now in the guide I am asked to catch two more pokemon(and as I understand it I just progress to day 5 and day 6, catching the pokemon that comes up). But the pokemon on day 5 is not a drifblim which totally messes with the input in the program...

Is this a bug in the program or am I understanding something incorrectly about the guide.
Thank you for your time and this awesome tool!

**Comment by Leanny** [comment]
Hi. Everything works as intended. The driftblim needs to be from date 4 as well and it will have the ivs the tool predicts. For day 5 and six you can use everything

**Comment by EmrXald** [comment]
Thanks for the clarification. I suspected as much really and kept through with your tutorial/documentation so naturally my concerns were answered below as you described and went through the UI of the program.
