### ISSUE TITLE
Unhandled Exception when starting search using CUDA

### ISSUE THREAD

**Issue by EmrXald** [Leanny/SeedSearcher#8]
EDIT: added more information about the problem!

Hi again!
Got an error with the exception code: [CUDAError]CUDA_ERROR_LAUNCH_FAILED
Below is a paste of the exceptions stack trace I would presume. I will also attach a screenshot of the data I submitted to your seed calculator.
![Shiny seed 2020-01-28 save file](https://user-images.githubusercontent.com/39636652/73299888-515a3e00-4210-11ea-87f2-d27bac741478.PNG)

I have a GTX 970 as GPU aswell.

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.Exception: [CUDAError] CUDA_ERROR_LAUNCH_FAILED
>    at Alea.CUDAInterop.cuSafeCall@2939.Invoke(String message)
>    at A.cf5aded17df9f7cc4c132234dda010fa7.Copy@918-22.Invoke(Unit _arg9)
>    at Alea.Memory.Copy(FSharpOption`1 streamOpt, Memory src, IntPtr srcOffset, Memory dst, IntPtr dstOffset, FSharpOption`1 lengthOpt)
>    at Alea.ImplicitMemoryTrackerEntry.cdd2cd00c052408bcdbf03958f14266ca(FSharpFunc`2 c600c458623dca7db199a0e417603dff4, Object cd5116337150ebaa6de788dacd82516fa)
>    at Alea.ImplicitMemoryTrackerEntry.c6a75c171c9cccafb084beba315394985(FSharpFunc`2 c600c458623dca7db199a0e417603dff4, Object cd5116337150ebaa6de788dacd82516fa)
>    at A.cf5aded17df9f7cc4c132234dda010fa7.HostReadWriteBarrierAll@2896.Invoke(Object instance, ImplicitMemoryTrackerEntry entry)
>    at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 495
>    at Alea.ImplicitMemoryTracker.cbcffd9b43091005a4b83b7c285d00cf4(FSharpFunc`2 c1adafcb76c9ccc7696ae17425ca36fc6)
>    at SeedSearcherGui.SeedSearcherGPU.SearchFour(Device device, Int32 start, Int32 end, ToolStripStatusLabel updateLbl)
>    at SeedSearcherGui.SeedSearcher.CalculateGPU(Int32 searcherIDX, Int32 minRerolls, Int32 maxRerolls, Int32[] target, ToolStripStatusLabel updateLbl)
>    at SeedSearcherGui.SeedSearcherGui.<>c__DisplayClass34_0.<SearchImpl>b__0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SeedSearcherGui.SeedSearcherGui.<SearchImpl>d__34.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>

**Comment by Leanny** [comment]
I added the solution to this in the readme a few minutes ago, but since I did not release a version with the file included, here a short guide:
* Download this file (ctrl + s and then save it as .bat file) https://raw.githubusercontent.com/Leanny/SeedSearcher/master/SeedSearcher/CudaSetup/EnableCuda.bat
* execute it as admin. This will increase CUDA timeout and tells your GPU not to shut down CUDA after 2 seconds automatically
* Reboot your PC

If this does not work, would you tell me your GPU? This was only tested with GTX970 and GTX980 so far

**Comment by EmrXald** [comment]
Damn that was a quick response! thank you! :)
I was in the midst of editing my original post with more information to try and help as much as I can when I saw your reply. So there should be some more info in the original post if that is of interest.

I will try out your solution! And my GPU is a GTX 970. ^^

**Comment by Leanny** [comment]
Yeah, please let me know if this works.
Also, even with GPU support a 4/6 search is quite slow right now (it doesnt take 8h per deviation, but it still takes around 15 minutes for me), so it might be better advance the frame and use a different (your frame 6 looks good, it will allow a 5/6 search which takes less time).

Also, is your frame 4 2nd Pkmn correct? Because Noctown and Corvi should both have the same ability (either 1 or 2) I think

**Comment by EmrXald** [comment]
I will try with this frame for a bit more but otherwise I will take your advice and advance the frame. At this point I have been fiddling with this so much and resetting so much I have kinda lost track of it all. Worst case I will have to try it tomorrow instead and give you an update then. It could very well be my ability is wrong because of this on the second pokemon :/

Interestingly after running the bat file and restarting the computer I have run into another exception instead:

> ************** Exception Text **************
> System.Exception: [CUDAError] CUDA_ERROR_UNKNOWN
>    at Alea.CUDAInterop.cuSafeCall@2939.Invoke(String message)
>    at A.cf5aded17df9f7cc4c132234dda010fa7.Copy@918-22.Invoke(Unit _arg9)
>    at Alea.Memory.Copy(FSharpOption`1 streamOpt, Memory src, IntPtr srcOffset, Memory dst, IntPtr dstOffset, FSharpOption`1 lengthOpt)
>    at Alea.ImplicitMemoryTrackerEntry.cdd2cd00c052408bcdbf03958f14266ca(FSharpFunc`2 c600c458623dca7db199a0e417603dff4, Object cd5116337150ebaa6de788dacd82516fa)
>    at Alea.ImplicitMemoryTrackerEntry.c6a75c171c9cccafb084beba315394985(FSharpFunc`2 c600c458623dca7db199a0e417603dff4, Object cd5116337150ebaa6de788dacd82516fa)
>    at A.cf5aded17df9f7cc4c132234dda010fa7.HostReadWriteBarrierAll@2896.Invoke(Object instance, ImplicitMemoryTrackerEntry entry)
>    at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 495
>    at Alea.ImplicitMemoryTracker.cbcffd9b43091005a4b83b7c285d00cf4(FSharpFunc`2 c1adafcb76c9ccc7696ae17425ca36fc6)
>    at SeedSearcherGui.SeedSearcherGPU.SearchFour(Device device, Int32 start, Int32 end, ToolStripStatusLabel updateLbl)
>    at SeedSearcherGui.SeedSearcher.CalculateGPU(Int32 searcherIDX, Int32 minRerolls, Int32 maxRerolls, Int32[] target, ToolStripStatusLabel updateLbl)
>    at SeedSearcherGui.SeedSearcherGui.<>c__DisplayClass34_0.<SearchImpl>b__0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SeedSearcherGui.SeedSearcherGui.<SearchImpl>d__34.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by Leanny** [comment]
Hm.. based on some google search I found the following things:
* Make sure your drivers are updated
* Launch the tool as admin

If this does not help as well, I will continue searching for the issue. As a quick input to test if the app is crashing or not:
Use Diglet (1 star) for each slot and only set HP to 31. Then you can get through all checks and can start a search. This should be the fastest way to test if it crashes or not

**Comment by EmrXald** [comment]
So I updated the drivers and launched it as admin to do the Diglet test and it went through the whole search and told me no seed was found. So if that is expected all seems to be working now!

**Comment by Leanny** [comment]
Yeah thats expected! I will close this issue now and you should be able to use GPU search now. If not please reopen the issue
